# These are supported funding model platforms
ko_fi: hoothin
custom: ["https://www.buymeacoffee.com/hoothin", "https://paypal.me/hoothin", "https://afdian.net/a/hoothin", "https://smms.app/image/lEqKWLHG7UBO6AY"]
